
# Menu section

# This is an example of the main menu. You can also use the in-file setting in the header of the content files. 

[[main]]
    identifier = "home"
    name = "Acasă"
    url = "/"
    weight = 10
[[main]]
    identifier = "scoala"
    name = "Școala"
    url = "/scoala"
    weight = 20
[[main]]
    identifier = "Oferta școlară"
    name = "Oferta"
    url = "/Oferta"
    weight = 30
[[main]]
    identifier = "Programe și proiecte"
    name = "Programe și proiecte"
    url = "/Programe și proiecte"
    weight = 40
[[main]]
    identifier = "Elevi"
    name = "Elevi"
    url = "/Elevi"
    weight = 50
[[main]]
    identifier = "Părinți"
    name = "Părinți"
    url = "/Părinți"
    weight = 60
[[main]]
    identifier = "Orar"
    name = "Orar"
    url = "/Orar"
    weight = 70
[[main]]
    identifier = "interes"
    name = "Interes public"
    url = "/Interes public"
    weight = 80
[[main]]
    identifier = "anunturi"
    name = "Anunțuri"
    url = "/Anunțuri"
    weight = 90
