
# Menu section

# This is an example of the main menu. You can also use the in-file setting in the header of the content files. 

[[main]]
    identifier = "acasa"
    name = "Acasă"
    pageRef = "/"
    weight = 10
[[main]]
    identifier = "prezentare"
    name = "Prezentare"
    pageRef = "/prezentare"
    weight = 20
     [[main]]
        identifier = "Despre"
        parent = "prezentare"
        name = "Despre"
        pageRef = "/prezentare/despre"
        weight = 1
    [[main]]
        identifier = "echipa"
        parent = "prezentare"
        name = "Echipa"
        pageRef = "/prezentare/echipa"
        weight = 2
    [[main]]
        identifier = "contact"
        parent = "prezentare"
        name = "Contact"
        pageRef = "/prezentare/contact"
        weight = 3
     [[main]]
        identifier = "Orar"
        parent = "prezentare"
        name = "Orar"
        pageRef = "/prezentare/Orar"
        weight = 4
    [[main]]
        identifier = "Repartitie"
        parent = "prezentare"
        name = "Repartitie"
        pageRef = "/prezentare/Repartitie"
        weight = 5
    [[main]]
        identifier = "documente"
        parent = "prezentare"
        name = "Documente"
        pageRef = "/prezentare/Documente"
        weight = 6
    [[main]]
        identifier = "CEAC"
        parent = "prezentare"
        name = "CEAC"
        pageRef = "/prezentare/CEAC"
        weight = 7
    [[main]]
        identifier = "50-Ani"
        parent = "prezentare"
        name = "Aniversare 50 Ani"
        pageRef = "/prezentare/50-Ani"
        weight = 8
[[main]]
    identifier = "Oferta"
    name = "Oferta"
    pageRef = "/Oferta"
    weight = 30
   [[main]]
        identifier = "inscrieri"
        parent = "Oferta"
        name = "Înscrieri clasa pregătitoare"
        pageRef = "/Oferta/Inscrieri"
        weight = 1
    [[main]]
        identifier = "primar"
        parent = "Oferta"
        name = "Învățământ primar"
        pageRef = "/Oferta/Primar"
        weight = 2
    [[main]]
        identifier = "gimnaziu"
        parent = "Oferta"
        name = "Învățământ gimnazial"
        pageRef = "/Oferta/Gimnaziu"
        weight = 3
    [[main]]
        identifier = "Asociația părintilor"
        parent = "Oferta"
        name = "Asociația Părinților"
        pageRef = "/Oferta/parinti"
        weight = 11   

[[main]]
    identifier = "programe-proiecte"
    name = "Programe și proiecte"
    pageRef = "/programe si proiecte"
    weight = 40
    [[main]]
        identifier = "Erasmus"
        parent = "programe-proiecte"
        name = "Erasmus+"
        pageRef = "/programe si proiecte/Erasmus+"
        weight = 1
    [[main]]
        identifier = "proiecte-educationale"
        parent = "programe-proiecte"
        name = "Proiecte educationale"
        pageRef = "/programe si proiecte/Proiecte educationale"
        weight = 2
    [[main]]
        identifier = "scoala-increderii"
        parent = "programe-proiecte"
        name = "Școala increderii"
        pageRef = "/programe si proiecte/Scoala increderii"
        weight = 3
[[main]]
    identifier = "elevi"
    name = "Elevi"
    pageRef = "/Elevi"
    weight = 50
    [[main]]
        identifier = "examene"
        parent = "elevi"
        name = "Examene"
        pageRef = "/Elevi/Examene"
        weight = 1
[[main]]
    identifier = "anunturi"
    name = "Anunțuri"
    pageRef = "/anunturi"
    weight = 60
