
# Menu section

# This is an example of the main menu. You can also use the in-file setting in the header of the content files. 

[[main]]
    identifier = "acasa"
    name = "Acasă"
    pageRef = "/"
    weight = 10
[[main]]
    identifier = "prezentare"
    name = "Prezentare"
    pageRef = "/prezentare"
    weight = 20
     [[main]]
        identifier = "Istoric"
        parent = "prezentare"
        name = "Scurt Istoric"
        pageRef = "/prezentare/Istoric"
        weight = 1
    [[main]]
        identifier = "echipa"
        parent = "prezentare"
        name = "Echipa"
        pageRef = "/prezentare/echipa"
        weight = 2
    [[main]]
        identifier = "contact"
        parent = "prezentare"
        name = "Contact"
        pageRef = "/prezentare/contact"
        weight = 3
     [[main]]
        identifier = "Orar"
        parent = "prezentare"
        name = "Orar"
        pageRef = "/prezentare/Orar"
        weight = 4
    [[main]]
        identifier = "Repartitie"
        parent = "prezentare"
        name = "Repartitia claselor"
        pageRef = "/prezentare/Repartitie"
        weight = 5
    [[main]]
        identifier = "documente"
        parent = "prezentare"
        name = "Documente publice"
        pageRef = "/prezentare/Documente"
        weight = 6
    [[main]]
        identifier = "CEAC"
        parent = "prezentare"
        name = "CEAC"
        pageRef = "/prezentare/CEAC"
        weight = 7
    [[main]]
        identifier = "50-Ani"
        parent = "prezentare"
        name = "Aniversare 50 Ani"
        pageRef = "/prezentare/50-Ani"
        weight = 8
[[main]]
    identifier = "Oferta"
    name = "Oferta"
    pageRef = "/Oferta"
    weight = 30
   [[main]]
        identifier = "inscrieri"
        parent = "Oferta"
        name = "Clasa pregătitoare"
        pageRef = "/Oferta/01_Inscrieri"
        weight = 1
    [[main]]
        identifier = "primar"
        parent = "Oferta"
        name = "Învățământ primar"
        pageRef = "/Oferta/02_Primar"
        weight = 2
    [[main]]
        identifier = "gimnaziu"
        parent = "Oferta"
        name = "Învățământ gimnazial"
        pageRef = "/Oferta/03_Gimnaziu"
        weight = 3
    [[main]]
        identifier = "CDS"
        parent = "Oferta"
        name = "CDS"
        pageRef = "/oferta/04_CDS"
        weight= 4
    [[main]]
        identifier = "Biblioteca"
        parent = "Oferta"
        name = "Biblioteca"
        pageRef = "/oferta/05_Biblioteca"
        weight= 5
    [[main]]
        identifier = "consilier"
        parent = "Oferta"
        name = "Cabinet consiliere"
        pageRef = "/oferta/06_Consilier"
        weight= 6
    [[main]]
        identifier = "logoped"
        parent = "Oferta"
        name = "Cabinet logopedie"
        pageRef = "/oferta/07_Logoped"
        weight= 7
     [[main]]
        identifier = "sprijin"
        parent = "Oferta"
        name = "Cabinet de sprijin"
        pageRef = "/oferta/08_Sprijin"
        weight= 8
    [[main]]
        identifier = "medic"
        parent = "Oferta"
        name = "Cabinet medical"
        pageRef = "/oferta/09_Medic"
        weight= 9
    [[main]]
        identifier = "secretariat"
        parent = "Oferta"
        name = "Secretariat"
        pageRef = "/oferta/10_Secretariat"
        weight= 10
    [[main]]
        identifier = "Administrativ-Contabilitate"
        parent = "Oferta"
        name = "Administrativ-Contabilitate"
        pageRef = "/oferta/11_Administrativ-Conta"
        weight= 11
    [[main]]
        identifier = "Asociația părintilor"
        parent = "Oferta"
        name = "Asociația Părinților"
        pageRef = "/Oferta/12_Parinti"
        weight = 12   
[[main]]
    identifier = "Examene"
    name = "Examene"
    pageRef = "/Examene"
    weight = 40
    [[main]]
        identifier = "Evaluare Națională-0246"
        parent = "Examene"
        name = "Evaluare Națională - 0246"
        pageRef = "/Examene/01_EN-0246"
        weight = 1
    [[main]]
        identifier = "Evaluare Natațională"
        parent = "Examene"
        name = "Evaluare Națională - 2024"
        pageRef = "/Examene/02_EvNat-08"
        weight = 2
    [[main]]
        identifier = "Simulari"
        parent = "Examene"
        name = "Simulari examene naționale"
        pageRef = "/Examene/03_Simulari"
        weight = 3
     [[main]]
        identifier = "Admitere"
        parent = "Examene"
        name = "Admitere 2024"
        pageRef = "/Examene/04_Admitere"
        weight = 4
[[main]]
    identifier = "Rezultate"
    name = "Rezultate"
    pageRef = "/Rezultate"
    weight = 50
    [[main]]
        identifier = "Olimpiade"
        parent = "Rezultate"
        name = "Rezultate meritorii"
        pageRef = "/Rezultate/01_Rezultate"
        weight = 1
    [[main]]
        identifier = "Concursuri"
        parent = "Rezultate"
        name = "Olimpiade și concursuri"
        pageRef = "/Rezultate/02_Concursuri"
        weight = 2
[[main]]
    identifier = "Reviste și publicații"
    name = "Reviste"
    pageRef = "/Reviste"
    weight = 60
    [[main]]
        identifier = "Revista InGEN1um"
        parent = "Reviste"
        name = "Revista InGEN1um"
        pageRef = "/Reviste/InGEN1um"
        weight = 1
    [[main]]
        identifier = "Revista Scientia Naturalis"
        parent = "Reviste"
        name = "Revista Scientia Naturalis"
        pageRef = "/Reviste/ScientiaNaturalis"
        weight = 2
    [[main]]
        identifier = "Revista Planeta Școala"
        parent = "Reviste"
        name = "Revista Planeta Școala"
        pageRef = "/Reviste/PlanetaScoala"
        weight = 3
    
[[main]]
    identifier = "Activități"
    name = "Activități"
    pageRef = "/Activitati"
    weight = 70
    [[main]]
        identifier = "Școala Altfel"
        parent = "Activități"
        name = "Școala Altfel"
        pageRef = "/Activitati/01_Altfel"
        weight = 1
    [[main]]
        identifier = "Săptămâna verde"
        parent = "Activități"
        name = "Săptămâna Verde"
        pageRef = "/Activitati/02_Verde"
        weight = 2
    [[main]]
        identifier = "Erasmus+"
        parent = "Activități"
        name = "Erasmus+"
        pageRef = "/Activitati/03_Erasmus+"
        weight = 3
    [[main]]
        identifier = "Școala Încrederii"
        parent = "Activități"
        name = "Școala Încrederii"
        pageRef = "/Activitati/03_Increderii"
        weight = 4
 [[main]]
 identifier = "Anunțuri"
    name = "Anunțuri"
    pageRef = "/Anunturi"
    weight = 80