
# Menu section

# This is an example of the main menu. You can also use the in-file setting in the header of the content files. 

[[main]]
    identifier = "acasa"
    name = "Acasă"
    pageRef = "/"
    weight = 10
[[main]]
    identifier = "scoala"
    name = "Școala"
    pageRef = "/scoala"
    weight = 20
[[main]]
    identifier = "oferta-scolara"
    name = "Oferta"
    pagteRef = "/oferta"
    weight = 30
[[main]]
    identifier = "programe-proiecte"
    name = "Programe și proiecte"
    pageRef = "/programe si proiecte"
    weight = 40
    [[main]]
        identifier = "Erasmus"
        parent = "programe-proiecte"
        name = "Erasmus+"
        pageRef = "/programe si proiecte/Erasmus+"
        weight = 1
    [[main]]
        identifier = "proiecte-educationale"
        parent = "programe-proiecte"
        name = "Proiecte educationale"
        pageRef = "/programe si proiecte/Proiecte educationale"
        weight = 2
    [[main]]
        identifier = "scoala-increderii"
        parent = "programe-proiecte"
        name = "Școala increderii"
        pageRef = "/programe si proiecte/Scoala increderii"
        weight = 3
[[main]]
    identifier = "elevi"
    name = "Elevi"
    pageRef = "/Elevi"
    weight = 50
    [[main]]
        identifier = "examene"
        parent = "elevi"
        name = "Examene"
        pageRef = "/Elevi/Examene"
        weight = 1
[[main]]
    identifier = "parinti"
    name = "Părinți"
    pageRef = "/parinti"
    weight = 60
[[main]]
    identifier = "orar"
    name = "Orar"
    pageRef = "/orar"
    weight = 70
[[main]]
    identifier = "interes"
    name = "Interes public"
    pageRef = "/interes public"
    weight = 80
[[main]]
    identifier = "anunturi"
    name = "Anunțuri"
    pageRef = "/anunturi"
    weight = 90
